### PR TITLE
Fuzzing integration

### PR DESCRIPTION
**Pull request by bookmoons**
Hello,

Interesting package. I think it's suitable for fuzzing. Proposing to get it running on [Fuzzit](https://fuzzit.dev/). They give free service for open source.

They use [go-fuzz](https://github.com/dvyukov/go-fuzz). It's one of these genetic fuzzers, it instruments the binary and tries to traverse all the branches. A local run has built up a corpus of a couple hundred cases. No crashes so far. It seems to be in good shape.

Build will fail due to missing the API key. If you're interested setup is like this:
* In Fuzzit create the target `panicparse`.
* In Fuzzit settings grab an API key. In repo settings in [Travis](https://travis-ci.org/) paste it to envvar `FUZZIT_API_KEY`.

### CODE REVIEW

**Comment by maruel** [comment]
What's the advantage of fuzzit versus fuzzbuzz?

**Comment by bookmoons** [comment]
Also seems nice! They seem to use the same fuzzers. Maybe it's worth getting them both running. The randomness means you'd increase chances of hitting a bug.

**Comment by bookmoons** [comment]
I see in the build you like to keep executables out of the repo. Pushed an update to move all of that into the Travis config.

**Comment by maruel** [comment]
Ok so I ran https://github.com/dvyukov/go-fuzz for over 2 hours on a 32 cores system, at a rate of ~120k exec/s and thankfully it didn't find anything but I don't think a web service would give much more than that. On the other hand I think committing the Fuzz function is useful, so I'd accept a PR with only this, this copyright header fixed and a docstring to explain how to use it and a link to https://github.com/dvyukov/go-fuzz.

**Comment by bookmoons** [comment]
Alright, thanks for looking at it.

**Pull request closed without merging**
