### PR TITLE
stack: export new ParseStack function

### LINKED ISSUE #50: How to parse a stacktrace?
There's a beautiful looking `Stack` struct that I'm hoping to be able to use, but I can't figure out how to generate it from a library. https://pkg.go.dev/github.com/maruel/panicparse/v2/stack#Stack

This is what I was expecting to find, but I can't see anything public that returns a `Stack`

```
// Library function
func ParseStack(stackBytes []byte) *Stack

// Usage
myStack := stack.ParseStack(debug.Stack())
```

My use case is that we wrap errors as we move up the stack and attach contextual data to each frame. We have our own internal stacktrace parser, but are hoping to swap it out for panicparse. Is this something you would like to support?

### PR DESCRIPTION
**Pull request by derekperkins**
fixes #50

### CODE REVIEW

**Comment by derekperkins** [comment]
If you're ok with adding this api, I'm happy to add a test

**Comment by maruel** [comment]
Can you expand on the use case? I'm not sure it is a frequent need, worth increasing the API surface. I generally prefer small API surface with o/nly one way of doing something", and I feel this would create two ways of doing one thing that is all in all, relatively trivial.

As such, I'd very like much see a new example in example_test.go named Example_simple() that would essentially be the code you put. Note that ScanSnapshot() will never return a *Snapshot without at least one goroutine in it so you can simplify the code there.

**Comment by derekperkins** [comment]
Before going further, I actually went ahead and tested this and it fails with an EOF error. I'm passing in `debug.Stack()` as the bytes that looks like this.

```
goroutine 11 [running]:
runtime/debug.Stack(0x1bd7be0, 0x0, 0x1c34860)
	/usr/local/Cellar/go/1.15.3/libexec/src/runtime/debug/stack.go:24 +0x9f
go.nozzle.io/pkg/e.TestParseStack.func1(0xc000602d80)
	/Users/derek/go/src/go.nozzle.io/pkg/e/stack_test.go:406 +0x45
testing.tRunner(0xc000602d80, 0xc00020e730)
	/usr/local/Cellar/go/1.15.3/libexec/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
	/usr/local/Cellar/go/1.15.3/libexec/src/testing/testing.go:1168 +0x2b3
```

**Comment by derekperkins** [comment]
Scratch that, I didn't realize that the `io.EOF` error was expected to be returned. After ignoring that error, things are working just as expected. I'll change this PR to be an example.

**Comment by maruel** [comment]
Thanks!

**Comment by derekperkins** [comment]
Just pushed it as an example. We rolled this out into production over the weekend and it's working great! Thanks for the awesome library!

**Comment by maruel** [comment]
Thanks!

**Comment by maruel** [comment]
I'll have to do a dot release for it to show up on pkg.go.dev, will do one before EOY.

**Pull request merged**
