### PR TITLE
Test with current development version

### PR DESCRIPTION
**Pull request by AlekSi**
To catch errors early.

### CODE REVIEW

**Comment by maruel** [comment]
I pondered this (but I was using tip) but decided against as I prefer reproducible tests, and in this case it is impossible to reproduce a run like this.

There's value on both side but I feel 1.x is already giving the best value here.

**Comment by maruel** [comment]
I'll close this PR as for now I don't want to have to manage inconsistent test executions, especially during the "development phase" of Go. See https://github.com/golang/go/wiki/Go-Release-Cycle#timeline for more details.

**Comment by AlekSi** [comment]
Well… Does it work with Go 1.9?

**Comment by maruel** [comment]
I use go 1.9 rc2 locally. You made me realize I should update now, so I did but there no new release yet. (I always build golang from sources)

**Comment by maruel** [comment]
and to be clear, `master` != `release-branch.go1.9`

**Pull request closed without merging**
