### PR TITLE
Add map and channel type

### PR DESCRIPTION
**Pull request by darrentu**
Added 2 missing types. I added the map and the channel type.

### CODE REVIEW

**Comment by maruel** [comment]
Oh, I see that fieldToType is currently covered only at 77.8%, would you mind increasing coverage?
https://coveralls.io/builds/11751554/source?filename=stack%2Fsource.go#L175

**Comment by maruel** [comment]
Would you mind signing the Google CLA at https://cla.developers.google.com/clas ?

**Comment by darrentu** [comment]
Where inside of source_test.go would you like me to add additional checks?

**Comment by maruel** [comment]
Add a new test function.

**Comment by maruel** [comment]
Ping.

**Pull request closed without merging**
