### PR TITLE
basic filter implementation

### PR DESCRIPTION
**Pull request by Dieterbe**
this addresses a common need for me. I often want to restrict output to
a certain package or set of files because i know that's where the stuff
is happening that I'm looking for.

here's some ideas to make this feature more advanced:
* both conditions are currently OR'ed. may want to change to AND, or
  leave it up to user. we may also want to support multiple conditions.
  something like the below perhaps:
  `-filter "path=foo && (package == bar || package == baz)"`
* instead of substring/equality, may want to support regex, especially for path

... I haven't personally had this need though, so I would keep it simple
until it's clear we want to support such fancier things.

### CODE REVIEW

**Comment by maruel** [comment]
That's an interesting idea and I can see a use case for this.

To become acceptable, it'd have to be unit tested a bit. Also, when there is no match, I'd prefer it to default to print everything vs not printing anything at all. Maybe with a warning, e.g. "warning: couldn't find requested signature, printing all traces\n".

I think I'd prefer to only have package and not path. In practice, I'd probably like it to be in the standard format, so that specifying "-filter-package ." would match everything in the current directory, and "-filter-package ./..." would match any package in the current directory or subdirectories. I understand this is significantly more work though but we could probably scavenge some prior work, for example in pcg. I'll think about it more today. Since there would only be one filter flag, it could be shortened to "-pkg".

**Comment by Dieterbe** [comment]
filtering by path is useful when you have a program with a lot of different files/"things" in the main package. i've seen some software (incl some of the things i write myself, but also others) that are designed like this.  the path fillter has helped me with finding issues in a specific file of the code that is in main pkg.

**Comment by maruel** [comment]
Ok, I'm not against, it's just that -pkg looks like having more obvious use cases to me. Still, there are a few issues I listed above.

**Comment by maruel** [comment]
You'll also want to merge conflicts with my latest change. Sorry for the breakage but this change had been queued up for several months (!) now.

**Comment by Dieterbe** [comment]
not sure why you want to tie the filtering so closely to the cwd of where pp is invoked?
most stacktraces i deal with are obtained from a running service and when i want to analyze them i'm typically not in the code directory. though i will go into code directories of the projects to look at code sure, but that's as-needed and can be with different projects. i don't see why i have to do the analysis of the stacktrace in the directory of the package i want to filter for. this seems clunky since i may want to switch back&forth with other packages from other projects, or even filter for 2 packages that are in different projects. but i also never quite grokked the syntax like `./..` etc, is that documented anywhere? it seems different than shell syntax. and would this allow filtering for 2 packages out of many in the same directory, or 2 packages that are in different paths?

**Comment by maruel** [comment]
You asked multiple questions, I'll try to address each individually.

1) There are two use cases:
- Processing traces from a remote service
- Processing traces at interactive prompt

It is important to distinguish both as each have their default use case that is fairly different. For example, there's no formal way to know what GOPATH was for remote traces, especially that it would be expected for the GOPATH (and even GOROOT) to be different.

2) When I said filtering base on package name, I gave ./... as an example but obviously arbitrary package path would have to be supported. You seem not familiar with ./..., it is fully documented at https://golang.org/cmd/go/#hdr-Relative_import_paths. For example you could use `-pkg github.com/maruel/panicparse/...` or if you happen to be in $GOPATH/src/github.com, `-pkg ./maruel/panicparse/...` would also happen to be valid.

3) You are asking for multiple packages. I think the most user friendly flow would be to use comma separated list. AFAIK comma can't be used in package name.

**Comment by Dieterbe** [comment]
re 1, yes very good point. i have a symlink `/home/ubuntu/.go_workspace -> /home/dieter/go` on my system to deal profiles i get from prod systems built through circle-ci for example. not very elegant but it's the best i could come up with to make the information show up properly when looking at profiles.

now things make more sense to me. i'll check out those docs. unfortunately it may take me quite a while to get to all this.

**Comment by maruel** [comment]
Do you plan to work on it in a timely manner? Otherwise I'd prefer to close the PR in the meantime. If you are unsure, we can close it then reopen later once you've made progress. Thanks.

**Pull request closed without merging**
